# Generated by Django 3.0.8 on 2020-12-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_supplier',
            new_name='is_company_owner',
        ),
        migrations.AddField(
            model_name='user',
            name='is_company_staff',
            field=models.BooleanField(default=False),
        ),
    ]
