# Generated by Django 3.0.8 on 2020-11-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_restaurant_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_restaurant_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_restaurant_staff',
            field=models.BooleanField(default=False),
        ),
    ]
