# Generated by Django 3.0.8 on 2020-11-04 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_restaurent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurent',
            new_name='Restaurant',
        ),
    ]
