# Generated by Django 3.0.8 on 2020-12-23 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20201222_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_company', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ManyToManyField(related_name='company_work_for', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='StaffDetail',
            new_name='UserDetail',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='price_by_supplier',
            new_name='price_by_supplier_company',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity_by_supplier',
            new_name='quantity_by_supplier_company',
        ),
        migrations.DeleteModel(
            name='SupplierDetail',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Company'),
        ),
    ]
