# Generated by Django 3.0.8 on 2020-12-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201223_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='phone_number',
            field=models.CharField(default=123456789, max_length=255),
            preserve_default=False,
        ),
    ]
