# Generated by Django 3.0.8 on 2020-12-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='delivered_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipped_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
