# Generated by Django 3.0.8 on 2020-12-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201227_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf_document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
