# Generated by Django 3.0.8 on 2020-12-28 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20201228_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='final_quantity',
        ),
    ]
