# Generated by Django 3.0.8 on 2020-12-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_orderitem_final_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='custom_status',
            field=models.CharField(choices=[('NOT_CUSTOM', 'NOT_CUSTOM'), ('CUSTOM', 'CUSTOM'), ('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], default='NOT_CUSTOM', max_length=255),
        ),
    ]
