# Generated by Django 3.0.8 on 2020-12-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20201204_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='editable',
            new_name='is_editable',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='item',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='items',
            field=models.ManyToManyField(to='products.OrderItem'),
        ),
    ]
