# Generated by Django 3.0.8 on 2020-12-05 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20201205_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Restaurant'),
        ),
    ]
