# Generated by Django 3.0.8 on 2021-01-05 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_restaurantorderitemhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantorderitemhistory',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Restaurant'),
        ),
    ]
