# Generated by Django 3.0.8 on 2020-12-05 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0018_orderitem_is_enquiry_solved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='being_delivered',
            new_name='is_delivered',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to=settings.AUTH_USER_MODEL),
        ),
    ]
