# Generated by Django 3.0.8 on 2020-12-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20201205_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='final_price',
            field=models.FloatField(default=0),
        ),
    ]
